### ISSUE TITLE
Undocumented methods of `fio.stat` and flags in `fio.c.<..>`

### ISSUE THREAD

**Issue by bigbes** [tarantool/doc#147]
```
tarantool> a = fio.stat('Makefile')
tarantool> type(a)
---
- table
...
tarantool> a
---
- inode: 202873036
  rdev: 0
  size: 7353
  atime: 1480650230.6111
  mode: 33204
  mtime: 1480650230.6111
  nlink: 1
  uid: 1000
  blksize: 4096
  gid: 1000
  ctime: 1480650230.6111
  dev: 64768
  blocks: 16
...
tarantool> getmetatable(a)
---
- __index:
    is_fifo: 'function: 0x41a41558'
    is_blk: 'function: 0x41a41530'
    is_reg: 'function: 0x41a414b8'
    is_sock: 'function: 0x41a415a8'
    is_chr: 'function: 0x41a41508'
    is_link: 'function: 0x41a41580'
    is_dir: 'function: 0x41a414e0'
...
```

`fio.stat` returns `table`, which contains methods:

* `is_reg` - analog of POSIX macro `S_ISREG`
* `is_fifo` - analog of POSIX macro `S_ISFIFO`
* `is_blk` - analog of POSIX macro `S_ISBLK`
* `is_sock` - analog of POSIX macro `S_ISSOCK`
* `is_chr` - analog of POSIX macro `S_ISCHR`
* `is_link` - analog of POSIX macro `S_ISLINK`
* `is_dir` - analog of POSIX macro `S_ISDIR`

also describe flags (simply, their existence), that are located in `fio.c`. They are necessary for `fio.stat` output understanding

```
tarantool> fio.c
---
- seek:
    SEEK_SET: 0
    SEEK_DATA: 3
    SEEK_HOLE: 4
    SEEK_END: 2
    SEEK_CUR: 1
  mode:
    S_IWGRP: 16
    S_IXGRP: 8
    S_IROTH: 4
    S_IXOTH: 1
    S_IRUSR: 256
    S_IXUSR: 64
    S_IRWXU: 448
    S_IRWXG: 56
    S_IWOTH: 2
    S_IRWXO: 7
    S_IWUSR: 128
    S_IRGRP: 32
  flag:
    O_NONBLOCK: 2048
    O_RDONLY: 0
    O_DIRECTORY: 65536
    O_WRONLY: 1
    O_ASYNC: 8192
    O_DIRECT: 16384
    O_NOATIME: 262144
    O_NOCTTY: 256
    O_PATH: 2097152
    O_SYNC: 1052672
    O_CLOEXEC: 524288
    O_TRUNC: 512
    O_NOFOLLOW: 131072
    O_RDWR: 2
    O_LARGEFILE: 0
    O_CREAT: 64
    O_APPEND: 1024
    O_NDELAY: 2048
    O_EXCL: 128
...
```
