### ISSUE TITLE
`errno` is not fully documented

### ISSUE THREAD

**Issue by bigbes** [tarantool/doc#148]
```
tarantool> getmetatable(errno)
---
- __newindex: 'function: 0x41666a38'
  __call: 'function: 0x41666890'
  __index:
    ENOLINK: 67
    EMSGSIZE: 90
    EOVERFLOW: 75
    ENOTCONN: 107
    EFAULT: 14
    EOPNOTSUPP: 95
    EEXIST: 17
    ENOSR: 63
    ENOTSOCK: 88
    EDESTADDRREQ: 89
    ...
...
```

`errno` module has list of errno's and, also, is callable by itself (returns current `errno` in number):

```
tarantool> errno
---
- strerror: 'function: 0x41666c98'
...
tarantool> errno()
---
- 0
...
```
