### ISSUE TITLE
[8pt] feedback: Binary protocol

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#1481]
> <…>D (0x41) + array of parameter values to match ? placeholders or **|:name placeholders|,**
> IPROTO_OPTIONS (0x2b) + array of options (usually empty).

https://www.tarantool.io/en/doc/2.4/dev_guide/internals/box_protocol/

There is no information how to bind named parameters. A client should wrap each element into a map, where the key holds a name of the parameter (with a colon) and the value is an actual value. So, to bind `foo` and `bar` to 42 and 43, a client should send `IPROTO_SQL_TEXT: <...>, IPROTO_SQL_BIND: [{"foo": 42}, {"bar": 43}]` (I use JSON notation for convenience, it is msgpack in real).

See https://github.com/tarantool/tarantool/blob/a1021237739b2c24be1252139fd66eae32c24884/src/box/bind.c#L52-L63

**Comment by Totktonada** [comment]
Update: Fixed `without a colon` → `with a colon`. I verified it and found that Lua API is the similar:

```yaml
tarantool> box.execute('select :bar, :foo', {{[':foo'] = 42}, {[':bar'] = 43}})
---
- metadata:
  - name: COLUMN_1
    type: integer
  - name: COLUMN_2
    type: integer
  rows:
  - [43, 42]
...
```

@Korablev77 Why it is not just a map in the binary protocol and Lua API both? It would be convenient for anyone I guess.
