### ISSUE TITLE
Document feedback_daemon report contents

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/doc#1749]
The doc contains a reference to feedback daemon [here](https://www.tarantool.io/en/doc/latest/reference/configuration/#feedback), but only lists 3 fields as part of its report.
Actually, feedback daemon's report contains much more info. We need to document all these fields.
Here's a feedback daemon report:
```
---
- arch: x64
```
^^^ Architecture tarantool was built for.
```
  features:
    schema:
      local_spaces: 0
      functional_indices: 0
      memtx_spaces: 0
      rtree_indices: 0
      tree_indices: 0
      temporary_spaces: 0
      jsonpath_indices: 0
      hash_indices: 0
      functional_multikey_indices: 0
      sync_spaces: 0
      vinyl_spaces: 0
      bitset_indices: 0
      jsonpath_multikey_indices: 0
```
^^^ Various index type counters, space type counters
```
    on_reload_configuration_used: false
```
^^^ Whether function `box.on_reload_configuration` is specified or not.
```
  cluster_id: 8b6692f1-5367-4232-8cf6-6a1a7f20303f
```
^^^ `box.info.cluster.uuid`
```
  tarantool_version: 2.8.0-0-gefc30ccf8
```
^^^ tarantool version
```
  stats:
    net:
      SENT:
        total: 0
      CONNECTIONS:
        current: 0
        total: 0
      REQUESTS:
        current: 0
        total: 0
      RECEIVED:
        total: 0
    box:
      DELETE:
        total: 0
      SELECT:
        total: 2
      INSERT:
        total: 0
      EVAL:
        total: 0
      CALL:
        total: 0
      PREPARE:
        total: 0
      EXECUTE:
        total: 0
      REPLACE:
        total: 0
      UPSERT:
        total: 0
      AUTH:
        total: 0
      ERROR:
        total: 0
      UPDATE:
        total: 0
    time: 1610608668528804
```
^^^ various network statistics and total count of performed operations together with system time of report generation
```
  os: OSX
```
^^^ Host os.
```
  options:
    replication_synchro_quorum: 1
    election_mode: off
    memtx_use_mvcc_engine: false
```
^^^ various configuration options used. Currently covers `box.cfg.replication_synchro_quorum`,
`box.cfg.election_mode`, `box.cfg.memtx_use_mvcc_engine`
```
  cgroup: 
```
^^^ process cgroup
```
  server_id: b35c01d5-3587-44e4-bb90-d7ae82dd64c2
```
^^^ `box.info.uuid`
```
  feedback_version: 5
...
```
