### ISSUE TITLE
Document new box.info.replication()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#186]
```
commit c9eb84e0f62028fe4eccd3397e27cc922eb3aa31
Author: Roman Tsisyk <roman@tarantool.org>
Date:   Mon Apr 10 15:08:06 2017 +0300

    replication: change box.info.replication output

    * Add box.info.replication[instance_id].id
    * Add box.info.replication[instance_id].lsn
    * Display all registered replicas in box.info.replication
    * Hide box.info.replication[instance_id].upstream when applier->state is OFF
    * Fix initial value of box.info.replication[instance_id].vclock
    * Add tests
```

### Example output

Master 1:
```
tarantool> box.info.replication
---
- 1:
    id: 1
    uuid: d0734943-1aaf-4db8-859d-b6bb5aa0921f
    lsn: 2
  2:
    id: 2
    uuid: 448997c0-b51e-4f22-9c2c-e0e5167b6910
    lsn: 0
    upstream:
      status: follow
      idle: 3.2325129508972
      lag: 0
    downstream:
      vclock: {1: 2}
```

Master 2:
```
tarantool> box.info.replication
---
- 1:
    id: 1
    uuid: d0734943-1aaf-4db8-859d-b6bb5aa0921f
    lsn: 2
    upstream:
      status: follow
      idle: 32.845174312592
      lag: 0
    downstream:
      vclock: {1: 2}
  2:
    id: 2
    uuid: 448997c0-b51e-4f22-9c2c-e0e5167b6910
    lsn: 0
...

```

**Comment by rtsisyk** [comment]
We forgot to change box.info.replication[x].upstream.error to contain an error object  instead of an error message.

**Comment by lenkis** [comment]
@rtsisyk getting a message for a disconnected instance at 1.7.4-52-g980d30092. is that what we want?

```
  replication:
    1:
      id: 1
      uuid: 1899631e-6369-40a1-81c9-7d170e909276
      lsn: 8
      upstream:
        status: disconnected
        idle: 53.800484895706
        message: connect, called on fd 18, aka 192.168.0.141:54425
        lag: 0
```
