### ISSUE TITLE
[1pt] feedback: Data model | Add a sharded space example

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#2474]
**Product:** Tarantool
**Audience/target:** dev
**Root document:** https://www.tarantool.io/en/doc/latest/book/box/data_model/
**SME:** @ Totktonada

# Details

The current example doesn't illustrate sharded spaces. It would be helpful if we reflected a sharding situation in the example. Check with the SME if we can replace the current example with the one below.

---

> <…>describe a data schema
> in the YAML format in a declarative way.
> **|The schema would look something like this|:**
> spaces:
>     users:
>       engine: memtx
>       is_local: false
>  <…>

https://www.tarantool.io/en/doc/latest/book/box/data_model/#data-schema-description-using-the-ddl-module

Create example for sharded space:

Something like this:

```yaml
spaces:
    users:
      engine: memtx
      is_local: false
      temporary: false
      format:
      - {name: user_id, type: uuid, is_nullable: false}
      - {name: fullname, type: string,  is_nullable: false}
      - {name: bucket_id, type: unsigned, is_nullable: false}
      indexes:
      - name: user_id
        unique: true
        parts: [{path: user_id, type: uuid, is_nullable: false}]
        type: HASH
      - name: bucket_id
        unique: false
        parts: [{path: bucket_id, type: unsigned, is_nullable: false}]
        type: TREE
      sharding_key: [user_id]
      sharding_func: test_module.sharding_func
```
