### ISSUE TITLE
 Memtx MVCC memory monitoring

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#2801]
**Root document:**
https://www.tarantool.io/en/doc/latest/book/monitoring/
https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_stat/

---

Introduce memtx MVCC memory monitoring. One can get it with
`box.stat.memtx.tx()` method or use index to access a particular
statistic. The statistics format:

```
txn:
  statements:
    max: 0
    avg: 0
    total: 0
  user:
    max: 0
    avg: 0
    total: 0
  system:
    max: 0
    avg: 0
    total: 0
mvcc:
  trackers:
    max: 0
    avg: 0
    total: 0
  conflicts:
    max: 0
    avg: 0
    total: 0
  tuples:
    tracking:
      stories:
        count: 0
        total: 0
      retained:
        count: 0
        total: 0
    used:
      stories:
        count: 0
        total: 0
      retained:
        count: 0
        total: 0
    read_view:
      stories:
        count: 0
        total: 0
      retained:
        count: 0
        total: 0
```

Requested by @drewdzzz in https://github.com/tarantool/tarantool/commit/5a99429f8cf230214736d4a0a3dbb566b42fe053.

**UPDATE(2.11.1)**: In the initial implementation (version 2.10.0 through 2.11.0 inclusive) `box.stat.memtx` wasn't callable. This was confusing because other stat entries (`box.stat.net`, `box.stat.vinyl`, `box.stat.sql`) are callable, see https://github.com/tarantool/tarantool/issues/8448. This was reworked in https://github.com/tarantool/tarantool/pull/8471. Now all memtx statistics can be obtained by calling `box.stat.memtx()` and to get memtx transaction statistics one should use `box.stat.memtx().tx`. It's still possible to call `box.stat.memtx.tx()` but this way is deprecated and left only for backward compatibility.
