### ISSUE TITLE
Cancel outdated workflow runs in documentation projects

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#3234]
When working on a feature branch, the author can sometimes push a quick fix before the previous commit has been built. There's no need to wait for it to build in such a case. Furthermore, unnecessary build takes CI time and wastes resources.

- [x] [tarantool/doc@`latest`](https://github.com/tarantool/doc/tree/latest) https://github.com/tarantool/doc/pull/3235
- [x] [tarantool/doc@`tt`](https://github.com/tarantool/doc/tree/tt) https://github.com/tarantool/doc/pull/3236
- [x] https://github.com/tarantool/enterprise_doc/tree/master https://github.com/tarantool/enterprise_doc/pull/198
- [x] https://github.com/tarantool/tdg-doc/tree/latest (2.x) https://github.com/tarantool/tdg-doc/pull/391
- [x] https://github.com/tarantool/tdg-doc/tree/master (1.x) https://github.com/tarantool/tdg-doc/pull/392
- [x] https://github.com/tarantool/tarantool-internals/tree/master https://github.com/tarantool/tarantool-internals/pull/42

We should automate canceling of a workflow run when a PR has been updated. Just like it works in tarantool/tarantool: 

https://github.com/tarantool/tarantool/blob/847e5e0c0468c53cbfe65257ca2e97a476f1c4ca/.github/workflows/centos_7.yml#L25-L32

```yaml
concurrency:
  # Update of a developer branch cancels the previously scheduled workflow
  # run for this branch. However, the 'master' branch, release branch (1.10,
  # 2.8, etc.), and tag workflow runs are never canceled.
  #
  # We use a trick here: define the concurrency group as 'workflow run ID' +
  # 'workflow run attempt' because it is a unique combination for any run.
  # So it effectively discards grouping.
  #
  # Important: we cannot use `github.sha` as a unique identifier because
  # pushing a tag may cancel a run that works on a branch push event.
  group: ${{ (
    github.ref == 'refs/heads/master' ||
    github.ref == 'refs/heads/1.10' ||
    startsWith(github.ref, 'refs/heads/2.') ||
    startsWith(github.ref, 'refs/tags/')) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true
```
