### ISSUE TITLE
Missing column name 'likes' from tutorial in try tarantool

### ISSUE THREAD

**Issue by mrpond** [tarantool/doc#3479]
# What needs to be done
space videos had no 'likes'
```
    videos:
        engine: memtx
        is_local: false
        temporary: false
        sharding_key:
        - "video_id"
        format:
        - {name: bucket_id, type: unsigned, is_nullable: false}
        - {name: video_id, type: uuid, is_nullable: false}
        - {name: description, type: string, is_nullable: true}
        indexes:
        - name: video_id
          unique: true
          parts: [{path: video_id, type: uuid, is_nullable: false}]
          type: HASH
        - name: bucket_id
          unique: false
          parts: [{path: bucket_id, type: unsigned, is_nullable: false}]
          type: TREE
```

but lua.api had

```
function add_video(request)
    local description = request:post_param("description")
    local result, err = crud.insert_object('videos', { video_id = uuid.new(), description = description, likes = 0 })
    if err ~= nil then
        return { body = json.encode({status = "Error!", error = err}), status = 500 }
    end

    return { body = json.encode({status = "Success!", result = result}), status = 200 }
end
```

error return with post data
`curl -X POST --data "description=My first tiktok" https://akkjpmuvfkt.try.tarantool.io/add_video`
`{"status":"Error!","error":{"line":152,"class_name":"InsertError","err":"Failed to flatten object: FlattenError: Object is specified in bad format: FlattenError: Unknown field \"likes\" is specified","file":"...ool\/try-cartridge\/.rocks\/share\/tarantool\/crud\/insert.lua","str":"InsertError: Failed to flatten object: FlattenError: Object is specified in bad format: FlattenError: Unknown field \"likes\" is specified"}}`

temporary fix add 'likes'
```
    videos:
        engine: memtx
        is_local: false
        temporary: false
        sharding_key:
        - "video_id"
        format:
        - {name: bucket_id, type: unsigned, is_nullable: false}
        - {name: video_id, type: uuid, is_nullable: false}
        - {name: description, type: string, is_nullable: true}
        - {name: likes, type: unsigned, is_nullable: false}
        indexes:
        - name: video_id
          unique: true
          parts: [{path: video_id, type: uuid, is_nullable: false}]
          type: HASH
        - name: bucket_id
          unique: false
          parts: [{path: bucket_id, type: unsigned, is_nullable: false}]
          type: TREE
```

result after fix

`curl -X POST --data "description=My first tiktok" https://akkjpmuvfkt.try.tarantool.io/add_video`
`{"status":"Success!","result":{"rows":[[11719,"b214fe02-7fe2-4dc6-9226-69d1eac4fda1","My first tiktok"]],"metadata":[{"type":"unsigned","name":"bucket_id","is_nullable":false},{"type":"uuid","name":"video_id","is_nullable":false},{"type":"string","name":"description","is_nullable":true}]}}`

**Reviewer:** @ documentarian name

# Definition of done

- [ ] do A
- [ ] do B

# Planning checklist

- [ ] Pick a label
- [ ] Estimate complexity in storypoints in the title
- [ ] Add to **Documentation** board → **Backlog**

> Note: issue templates are in beta. Give your feedback in #1869.
