### ISSUE TITLE
Document box.info.replicaiton[x].peer

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/doc#354]
```
tarantool> box.info.replication
---
- 1:
    id: 1
    uuid: cfcb8006-781b-4e2b-bbfb-c95594f15553
    lsn: 91208
    upstream:
      status: follow
      idle: 2.0781464660249
      peer: 127.0.0.1:3313
      lag: 0
  2:
    id: 2
    uuid: 21dbba9d-39cd-484c-b49a-b647710992df
    lsn: 0
...
```

https://github.com/tarantool/tarantool/issues/2689
