### ISSUE TITLE
[Config] Update the 'Starting and stopping instances' guide to using a new config

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#3791]
**Related docs. issue(s):** https://github.com/tarantool/doc/issues/3847

**Product:** Tarantool
**Since:** 3.0
**Root document:** https://www.tarantool.io/en/doc/latest/book/admin/start_stop_instance/
**SME:** @ Totktonada

**Example**

tt configuration structure:

```
└── instances.enabled
    └── app
        ├── config.yaml
        └── instances.yml
```

`config.yaml`:

```
credentials:
  users:
    replicator:
      password: 'topsecret'
      roles: [replication]
    client:
      password: 'secret'
      roles: [super]

iproto:
  advertise:
    peer: replicator@

replication:
  failover: election

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            iproto:
              listen: 127.0.0.1:3301
          instance-002:
            iproto:
              listen: 127.0.0.1:3302
          instance-003:
            iproto:
              listen: 127.0.0.1:3303
```

`instances.yaml`:

```
app.instance-001:

app.instance-002:

app.instance-003:
```

Run app:

```
tt start app
```
