### ISSUE TITLE
[Config] Update the 'Managing modules' guide to using a new config

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#3812]
**Product:** Tarantool
**Since:** 3.0
**Root document:** https://www.tarantool.io/en/doc/latest/book/admin/modules/
**SME:** @ Totktonada

**Example**

Loading an app:

```
app:
  file: 'myapp.lua'
  cfg:
    greeting: 'Hello'
```
