### ISSUE TITLE
 config: support {{ replicaset_name }} and {{ group_name }}

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#3835]
The declarative configuration supports `{{ instance_name }}` template
variable from the beginning.

Now, two more ones were added: `{{ replicaset_name }}` and
`{{ group_name }}`.

All the template variables are set according to the
instance/replicaset/group topology from the given configuration.

Example:

```yaml
console:
  socket: '{{ group_name }}/{{ replicaset_name }}/{{ instance_name }}.admin'

groups:
  g:
    replicasets:
      r:
        instances:
          i: {}
```

The admin console will be at `g/r/i.admin` for instance `i`.

Requested by @Totktonada in https://github.com/tarantool/tarantool/commit/f059973d2038c0a0b61d31dcf0b581eca8f1eee4.
