### ISSUE TITLE
 Document `space:stat()`

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#3841]
**Related dev. issue(s):** https://github.com/tarantool/tarantool/issues/6762
**Related doc. issue(s):** https://github.com/tarantool/doc/issues/3840

**Product:** Tarantool
**Since:** 3.0
**Root document:** Root document: https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/
**SME:** @ Gumix

# Details

`space_object:stat()` — Get statistics on the memory usage

Returns a table with the cumulative statistics on the memory usage by tuples in the space. The statistics is grouped by arena types: "memtx" or "malloc". For a detailed description of each field see `tuple_object:info()` (https://github.com/tarantool/doc/issues/3840).

Note: The statistics is collected only for memtx storage engine. For other types of spaces, an empty table is returned.

Example:

```yaml
tarantool> box.space.test:stat()
---
- tuple:
    memtx:
      data_size: 5100699
      header_size: 96
      field_map_size: 40
      waste_size: 143093
    malloc:
      data_size: 18850077
      header_size: 70
      field_map_size: 28
      waste_size: 0
...
```
Requested by @ Gumix in https://github.com/tarantool/tarantool/commit/45f9759f6531afc9e0eeee6d5ce0e2da24dbb38f.
