### ISSUE TITLE
 config: compat options

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#3937]
**Related dev. issue(s):** https://github.com/tarantool/tarantool/issues/9497
**Duplicate:** https://github.com/tarantool/doc/issues/4021

**Product:** Tarantool
**Since:** 3.0
**Root document:** 

- A new `compat` section in the [Configuration reference](https://www.tarantool.io/en/doc/latest/reference/configuration/configuration_reference/). Each option can have a short description with a link to a corresponding page in [Module compat](https://www.tarantool.io/en/doc/latest/reference/reference_lua/compat/).

**SME:** @ Totktonada

# Details

The new section `compat` is added to the declarative configuration.

The options are the same as ones provided by the `compat` module. Each
can be set to `old` or `new`.

Example:

```yaml
compat:
  json_escape_forward_slash: old
```

The list of currently supported options with their defaults:

```yaml
compat:
  json_escape_forward_slash: new
  yaml_pretty_multiline: new
  fiber_channel_close_mode: new
  box_cfg_replication_sync_timeout: new
  sql_seq_scan_default: new
  fiber_slice_default: new
  box_info_cluster_meaning: new
  binary_data_decoding: new
  box_tuple_new_vararg: new
  box_session_push_deprecation: old
  sql_priv: new
  c_func_iproto_multireturn: new
  box_space_execute_priv: new
  box_tuple_extension: new
  box_space_max: new
...
```

The `box_cfg_replication_sync_timeout` option is non-dynamic and it
can't be changed after a startup.

Technically, all the other options could be changed in runtime (by
changing the configuration file and calling `config:reload()`), but I
would not generally recommend it.

At least code that handles `fiber_channel_close_mode` option has the
following comment, see commit de9b93081873 ("fiber: add channel close
mode option to compat").

> The behavior is unspecified for already created channels.
> Choose the mode at an early stage of application's
> initialization.

Requested by @ Totktonada in https://github.com/tarantool/tarantool/commit/317dc0376b5adc3ca235f684ab8b8775c5581292.
