### ISSUE TITLE
 vshard: vshard.router.info shows name

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#3944]
**Related dev. issue:** https://github.com/tarantool/vshard/issues/426
**Related doc. issues:** https://github.com/tarantool/doc/issues/3942, https://github.com/tarantool/doc/issues/3943

**Product:** Tarantool, vshard
**Since:** 3.0, 0.1.25
**Root document:** https://www.tarantool.io/en/doc/latest/reference/reference_rock/vshard/vshard_router/
**SME:** @ Totktonada, @ Serpentian

# Details

When `identification_mode` is `name_as_key`, persisted master and
replicaset name is shown in vshard.router.info:

```
tarantool> vshard.router.info()
---
- replicasets:
    replicaset_1:
      replica: &0
        network_timeout: 0.5
        status: available
        uri: storage@127.0.0.1:3303
        name: replica_1_a
      name: replicaset_1
      master: *0
```
Requested by @Serpentian in https://github.com/tarantool/vshard/commit/4c14eb46a25b3428599570cc582ea4b82b31d4b6.
