### ISSUE TITLE
 New labels in config schema

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#4096]
**Related dev. issue(s):** https://github.com/tarantool/tarantool/issues/9809

**Product:** Tarantool
**Since:** 3.1
**Root document:** 
- https://www.tarantool.io/en/doc/latest/concepts/configuration/
- https://www.tarantool.io/en/doc/latest/reference/configuration/configuration_reference/
- https://www.tarantool.io/en/doc/latest/release/3.1.0/#experimental-connpool-module
- Mongodb docs for tags: https://www.mongodb.com/docs/manual/tutorial/configure-replica-set-tag-sets/

**SME:** @ Lord-KA

# Details

The new labels are basically maps with string keys and values,
that are merged down to instance level. It means that if a replicaset
and an instance inside it have label with same key and different
value, the actual value is the one instance provided, e.g.

```yaml
groups:
  group-001:
    replicasets:
      replicaset-001:
        labels:
          foo: 'true'
          bar: 'true'
        instances:
          instance-001:
            labels:
              baz: 'true'
              foo: 'false'
```

Results in:

```
./instance-001.iproto> require('config'):get('labels')
---
- baz: 'true'
  foo: 'false'
  bar: 'true'
...
```
Requested by @ Lord-KA in https://github.com/tarantool/tarantool/commit/6d46a04c6f08e2fb450485cbd6dcaddc59460a59.
