### ISSUE TITLE
TCS: scheduler metrics

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#4339]
**Related dev. resources:**
* TCS roadmap: https://www.notion.so/tarantool/TSC-933d545852824f5abefa189881a801a8#add621ee191e438d91bb27bf19638159
* TCS releases Q2-Q3: https://www.notion.so/tarantool/TCS-Q2-Q3-2024-2844bf3db1184e7c939686e2ea0c9362
* TCS deliverables June 30: https://www.notion.so/tarantool/DELIVERABLE-30-2024-5c7068cf14fb4ea689d9c7ada9ebf551
* Dev ticket: https://www.notion.so/tarantool/Scheduler-f1e53dee9a7f46c68b01c5bd76ad0537
* TCS metrics: https://www.notion.so/tarantool/TCS-de5e9c30a3384960a5c885afee61c25f

**Product:** TCS
**Since:** release 0.18 (June 30)
**Audience/target:** end users (finops)
**Root document:** https://docs.d.tarantool.io/ru/column-store/doc/latest/
**SME:** @ Galiev-Ruslan @ stepanpopov 

## Details

В конфиг шедулера была добавлена опция:
pub with_metrics: bool
дефолтное значение - false

выглядит вот так:
```
listen: 0.0.0.0:7778
with_metrics: false
features:
  - experimental_api
nodes:
  - admin_iproto_endpoint: localhost:3301
    admin_http_endpoint: localhost:8081
    api_http_endpoint: localhost:7777
  - admin_iproto_endpoint: localhost:3302
    admin_http_endpoint: localhost:8082
    api_http_endpoint: localhost:7776
```
