### ISSUE TITLE
 Support of timestamp field in :totable()

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#4437]
The field `timestamp` is available in a table produced by
`:totable`:

```
tarantool> datetime.new({timestamp=100}):totable()
---
- timestamp: 100
  tz:
  sec: 40
  min: 1
  yday: 1
  day: 1
  nsec: 0
  isdst: false
  wday: 5
  tzoffset: 0
  month: 1
  year: 1970
  hour: 0
...

tarantool>
```
Requested by @ligurio in https://github.com/tarantool/tarantool/commit/f66020b670296642547cbfe0a34ab6c11d69989d.
