### ISSUE TITLE
TCF (0.5.0): support TLS for destination/gateway

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4542]
**GH repo:** https://github.com/tarantool/cluster-federation
**Related issue:** https://jira.vk.team/browse/TNTP-302
**PM ref.:** https://www.notion.so/tarantool/TCF-17ebdcdd3acd4752bab530b254972d79
**Root document:** https://www.tarantool.io/en/clustersfederation/doc/latest/references/

# Details

Нужно занести в справочник опции для настройки TLS/SSL.

Верхнеуровнево фича описана в what's new tcf: https://www.tarantool.io/en/clustersfederation/doc/latest/whats_new_tcf/#tls

1) https://github.com/tarantool/cluster-federation/pull/271

Пример конфигурации:

```
gateway:
  grpc_server:
    host: 0.0.0.0
    port: 10080
    ssl_cert_file: /path/to/server.crt
    ssl_key_file: /path/to/server.key
    ssl_ca_file: /path/to/ca.crt

destination:
  gateway:
    host: localhost
    port: 10080
    ssl_cert_file: /path/to/server.crt
    ssl_key_file: /path/to/server.key
    ssl_ca_file: /path/to/ca.crt
```

2) https://github.com/tarantool/cluster-federation/pull/262
