### ISSUE TITLE
 Use priorities when bootstrapping replica in supervised mode

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#4565]
**Product:** Tarantool
**Since:** 3.3.0
**Root document:** 
- https://www.tarantool.io/en/doc/latest/reference/configuration/configuration_reference/
- (?) https://www.tarantool.io/en/doc/latest/platform/replication/supervised_failover/
**SME:** @ georgiy-belyanin 

# Details

Now, when working in `replication.failover = supervised` mode the
instance priorities specified in the
`failover.replicasets.<replicaset-name>.priority` section are used
to select the bootstrap leader when using `bootstrap_strategy: auto`.
The replica with the highest priority is chosen as a bootstrap leader.
If there are more than one instance with the highest priority the first
one sorted by name alphabetically is chosen.

Example:
```yaml
replication:
  failover: supervised
failover:
  replicasets:
    replicaset-001:
      priority:
        instance-002: 5
        instance-003: -3
        instance-004: 5
```
Setting up the config like this will make Tarantool choose
`instance-002` as the bootstrap leader.
Requested by @georgiy-belyanin in https://github.com/tarantool/tarantool/commit/2eee236f1e866a53daf1b02832ee022727770d22.
