### ISSUE TITLE
 Allow multiple directories with modules

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#4664]
The logic of working with configuration file tt.yaml has been updated,
now  modules/directory can be specified both as a single line and
as a list.

**Usage example**
Old behavior:
```yaml
modules:
  directory: modules
```
Possibility to specify a list of directories:
```yaml
modules:
  directory:
  - modules
  - /ext/path/modules
  - other_modules
```

If a relative path is specified, the search is performed in
the subfolders below, relative to the tt.yaml file. If an absolute
path is specified, external modules are searched according to
the specified path.
Requested by @dmyger in https://github.com/tarantool/tt/commit/139119eedc281b5b8545b7d8e0f492f55d965b7e.
