### ISSUE TITLE
 Suggest new bootstrap strategies in the supervised failover guide

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#5080]
Now supervised failover coordinator supports three bootstrap strategies:
`native`, `supervised`, `auto`. It's suggested to use on of the first
since they behave more native for the failover coordinator.

That's how the suggested cluster's configuration `replication` section
should be changed.

```yaml
 replication:
   failover: supervised
+  bootstrap_strategy: native
```
Requested by @georgiy-belyanin in https://github.com/tarantool/tarantool-ee/commit/6183eb8425f7c9a8d63f1f5b09caead095bf113a.
