### ISSUE TITLE
feedback: Configuration | Tarantool

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#5087]
> <…>nted in the Configuration reference.
> 
> 
> 
> Configuration in a file
> **|This section provides an overview on how to configure Tarantool in a YAML file.|**
> 
> Basic instance configuration
> The example below shows a sample <…>

https://www.tarantool.io/en/doc/latest/platform/configuration/#configuration

Let's add here link for json-schema (which enables annotations in text editor of all available configurations of tarantool).

File should be started with:

# yaml-language-server: $schema=https://download.tarantool.org/tarantool/schema/config.schema.json

**Comment by ochaton** [comment]
For example:

```yaml
# yaml-language-server: $schema=https://download.tarantool.org/tarantool/schema/config.schema.json
groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
              - uri: '127.0.0.1:3301'

```
