### ISSUE TITLE
TCF (0.9.0): introduce dial_timeout filed in destination for gateways pool

### ISSUE THREAD

**Issue by themilchenko** [tarantool/doc#5113]
Product: TCF
Since: 0.9.0
Audience/target: admin
Root document: [where to add or update documentation](https://www.tarantool.io/en/clustersfederation/doc/latest/references/configuration_reference_replicator/#destination-gateways)
SME: @themilchenko

### Details

В *destination* появились новые опции в полях *gateway* и *gateways* (для каждого элемента списка) - *dial_timeout*. Опция обозначает время (таймаут), в течение которого клиент destination пытается подключиться к соответствующему инстансу gateway по gRPC.

Формат значения - строка. Указывается число, затем размерность. Например, "6s", "1m", "500ms" и т.д.

В случае, если эта опция не указывается, используется значение по умолчанию: 5 секунд.

Пример конфигурации в случае, когда один gateway:

```yaml
destination:\
  gateway:\
    host: localhost
    port: 10080
    dial_timeout: "3s"
```

Пример конфигурации в случае, когда несколько инстансов (пул) gateway:

```yaml
destination:\
  gateways:\
  - host: localhost
    port: 10080
    dial_timeout: "3s"
```

[Merge Request](https://gitlab.corp.mail.ru/tarantool/tcf/clusters-federation/-/merge_requests/15)
