### ISSUE TITLE
 box.error.new() - create an error object with no throw

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#512]
`box.error.new(error_code, args)` - the way to create an error object and do not throw it, but just return as the simple object. It is useful when an error object must be saved to be got later, for example.
``` YAML
tarantool> e = box.error.new(box.error.CREATE_SPACE, "space", "error")
tarantool> e
---
- 'Failed to create space ''space'': error'
...
tarantool> e:unpack()
---
- type: ClientError
  code: 9
  message: 'Failed to create space ''space'': error'
  trace:
  - file: '[string "e = box.error.new(box.error.CREATE_SPACE, "sp..."]'
    line: 1
...
```
Requested by @Gerold103 in https://github.com/tarantool/tarantool/issues/3031.
