### ISSUE TITLE
CSS Auto-prefixer

### ISSUE THREAD

**Issue by mejedi** [tarantool/doc#78]
Integrate auto-prefixer in the build process. Drop explicit prefixes in CSS.

Ex:

``` css
.b-download-list-item-drop {
    -webkit-transition: all 0.2s ease-in-out;
    -moz-transition: all 0.2s ease-in-out;
    -o-transition: all 0.2s ease-in-out;
    -ms-transition: all 0.2s ease-in-out;
    transition: all 0.2s ease-in-out;
}
```
